"""Generate responsive browsing copies; never overwrite original photographs.

Requires Pillow. Run from the repository root:
node scripts/image-input.cjs | python scripts/optimize-images.py
"""
import hashlib
import json
import sys
from pathlib import Path
from PIL import Image, ImageOps

root = Path(__file__).resolve().parents[1]
output = root / 'images' / 'optimized'
output.mkdir(parents=True, exist_ok=True)
products = json.load(sys.stdin)
manifest = {}
for product in products:
    for index, source in enumerate(product['images']):
        if source in manifest:
            continue
        original = root / source
        digest = hashlib.sha256(original.read_bytes()).hexdigest()[:10]
        with Image.open(original) as image:
            photo = ImageOps.exif_transpose(image)
            photo = photo.convert('RGBA' if 'A' in photo.getbands() else 'RGB')
            variants = []
            for width in sorted({min(size, photo.width) for size in (320, 640, 960)}):
                height = round(photo.height * width / photo.width)
                name = f'{product["id"]}-{index + 1}-{digest}-{width}.webp'
                target = output / name
                if not target.exists():
                    resized = photo.resize((width, height), Image.Resampling.LANCZOS)
                    resized.save(target, 'WEBP', quality=86, method=6,
                                 icc_profile=image.info.get('icc_profile', b''))
                variants.append({'src': f'images/optimized/{name}', 'width': width,
                                 'bytes': target.stat().st_size})
            manifest[source] = {'width': photo.width, 'height': photo.height,
                                'bytes': original.stat().st_size, 'variants': variants}

destination = root / 'image-manifest.js'
destination.write_text('// Generated by scripts/optimize-images.py. Do not edit by hand.\n'
                       + 'const productImageManifest = ' + json.dumps(manifest, indent=2) + ';\n',
                       encoding='utf-8')

# The source favicon is much larger than its display size. Keep it untouched and
# publish a compact square copy for every page.
with Image.open(root / 'images' / '48x48.png') as icon:
    icon = ImageOps.exif_transpose(icon).convert('RGBA')
    icon.thumbnail((48, 48), Image.Resampling.LANCZOS)
    icon.save(root / 'images' / 'favicon-48.png', 'PNG', optimize=True)
main = [manifest[p['images'][0]] for p in products]
print(json.dumps({'photos': len(manifest), 'catalogOriginalBytes': sum(x['bytes'] for x in main),
                  'catalog320Bytes': sum(x['variants'][0]['bytes'] for x in main),
                  'catalog640Bytes': sum(x['variants'][min(1,len(x['variants'])-1)]['bytes'] for x in main)}))
